name: Treelife_Core
version: ${project.version}
main: me.Maiky1304.treelife.main.Main
api-version: 1.13
authors: [Maiky1304]
website: https://www.minetitan.nl
commands:
  vehicle:
    description: Hiermee kun je de voertuigen beheren.
  vehicleadmin:
    description: Admin commando voor vehicle